# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
from pathlib import Path
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, Label,messagebox,PhotoImage
import sqlite3, sys, subprocess
# Capture the car_id from the command-line argument
from PIL import Image, ImageTk
from tkcalendar import DateEntry
from datetime import datetime

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\car rental booking system\build\assets\frame0")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def go_back():
    window.destroy()
    subprocess.Popen([sys.executable, "car.py"])

def create_bookings_table():
    try:
        conn = sqlite3.connect(r"C:\car rental booking system\Car-Booking\Users.db")
        cursor = conn.cursor()
        cursor.execute(''' 
            CREATE TABLE IF NOT EXISTS bookings (
                booking_id INTEGER PRIMARY KEY AUTOINCREMENT,
                car_id INTEGER,
                customer_name TEXT,
                email TEXT,
                contact_number TEXT,     
                date_of_birth TEXT,    
                rental_start_date TEXT,    
                rental_end_date TEXT,
                total_price REAL,
                status TEXT DEFAULT 'Pending',
                FOREIGN KEY(car_id) REFERENCES cars(id)
            )
        ''')
        conn.commit()
        print("Bookings table created successfully.")
    except sqlite3.Error as e:
        print("Error creating bookings table:", e)
    finally:
        conn.close()

create_bookings_table()

window = Tk()
window.geometry("1221x773")
window.configure(bg="#FFFFFF")

def connect_db():
    return sqlite3.connect(r"C:\car rental booking system\Car-Booking\Users.db")

# Ensure bookings table is created
def get_selected_car_details(car_id):
    conn = connect_db()
    cursor = conn.cursor()
    cursor.execute("SELECT make_and_model, daily_rate, seating_capacity, car_type, transmission_type, image_path FROM cars WHERE id = ?", (car_id,))
    car = cursor.fetchone()
    conn.close()
    return car

def create_booking_page(car_id):
    # Create the Tkinter window once
    global window
    if 'window' not in globals() or not window.winfo_exists():
        window = Tk()

    car_details = get_selected_car_details(car_id)
    if not car_details:
        print("Car details not found.")
        return

    make_and_model, daily_rate, seating_capacity, car_type, transmission_type, image_path = car_details

    selected_car = {
        'make_and_model': make_and_model,
        'daily_rate': daily_rate,
        'seating_capacity': seating_capacity,
        'car_type': car_type,
        'transmission_type': transmission_type,
        'image_path': image_path
    }
    # Clear any existing widgets on the canvas if needed
    for widget in window.winfo_children():
        widget.destroy()

    # Canvas creation for layout
    canvas = Canvas(window, bg="#FFFFFF", height=773, width=1221, bd=0, highlightthickness=0, relief="ridge")
    canvas.place(x=0, y=0)

    canvas.create_rectangle(
        0.0,
        0.0,
        1221.0,
        113.0,
        fill="#DFDFDF",
        outline="")

    if image_path:
        try:
            pil_image = Image.open(image_path)  # Open image from file path
            resized_image = pil_image.resize((250, 200), Image.LANCZOS)  # Resize if needed
            image_to_display = ImageTk.PhotoImage(resized_image)

            # Place the image on the canvas
            canvas.create_image(
                250, 150,  # Adjust these coordinates to position the image within the blue area
                image=image_to_display,
                anchor="nw"
            )

            # Retain a reference to prevent garbage collection
            canvas.image_to_display = image_to_display
        except Exception as e:
            print("Error loading image:", e)

    car_brand_label = Label(window, text=f"{make_and_model}", font=("Arial", 14, "bold"), bg="#FFFFFF")
    car_price_label = Label(window, text=f"Price: RM {daily_rate}", font=("Arial", 12), bg="#FFFFFF")
    car_seats_label = Label(window, text=f"Seats: {seating_capacity}", font=("Arial", 12), bg="#FFFFFF")
    car_type_label = Label(window, text=f"Car Type: {car_type}", font=("Arial", 12), bg="#FFFFFF")
    car_transmission_label = Label(window, text=f"Transmission: {transmission_type}", font=("Arial", 12),
                                   bg="#FFFFFF")
    car_brand_label.place(x=50, y=200)
    car_price_label.place(x=50, y=230)
    car_seats_label.place(x=50, y=260)
    car_type_label.place(x=50, y=290)
    car_transmission_label.place(x=50, y=320)

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        86.0,
        57.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=1126.0,
        y=31.0,
        width=49.0,
        height=49.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat"
    )
    button_2.place(
            x=969.0,
            y=36.0,
            width=132.0,
            height=40.0
        )

    button_image_3 = PhotoImage(
            file=relative_to_assets("button_3.png"))
    button_3 = Button(
            image=button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_3 clicked"),
            relief="flat"
        )
    button_3.place(
            x=700.0,
            y=30.0,
            width=84.0,
            height=52.0
        )

    button_image_4 = PhotoImage(
             file=relative_to_assets("button_4.png"))
    button_4 = Button(
            image=button_image_4,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_4 clicked"),
            relief="flat"
        )
    button_4.place(
            x=854.0,
            y=30.0,
            width=90.0,
            height=52.0
        )

    button_image_5 = PhotoImage(
            file=relative_to_assets("button_5.png"))
    button_5 = Button(
            image=button_image_5,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_5 clicked"),
            relief="flat"
        )
    button_5.place(
            x=784.0,
            y=30.0,
            width=70.0,
            height=52.0
        )

    canvas.create_text(
            39.0,
            125.0,
            anchor="nw",
            text="BOOK A CAR",
            fill="#000000",
            font=("KaiseiDecol Medium", 30 * -1)
        )

    canvas.create_text(
            39.0,
            394.0,
            anchor="nw",
            text="Name:",
            fill="#000000",
            font=("KaiseiDecol Medium", 20 * -1)
        )

    canvas.create_text(
            39.0,
            451.0,
            anchor="nw",
            text="Email:",
            fill="#000000",
            font=("KaiseiDecol Medium", 20 * -1)
        )

    canvas.create_text(
            39.0,
            565.0,
            anchor="nw",
            text="Date of birth:",
            fill="#000000",
            font=("KaiseiDecol Medium", 20 * -1)
        )

    canvas.create_text(
            550.0,
            394.0,
            anchor="nw",
            text="Rental Start Date:",
            fill="#000000",
            font=("KaiseiDecol Medium", 20 * -1)
        )

    canvas.create_text(
            550.0,
            451.0,
            anchor="nw",
            text="Rental End Date:",
            fill="#000000",
            font=("KaiseiDecol Medium", 20 * -1)
        )

    canvas.create_text(
            39.0,
            508.0,
            anchor="nw",
            text="Contact Number:",
            fill="#000000",
            font=("KaiseiDecol Medium", 20 * -1)
        )

    name_entry = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0
        )
    name_entry.place(
            x=110.0,
            y=394.0,
            width=277.0,
            height=28.0
        )

    email_entry = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0
        )
    email_entry.place(
            x=110.0,
            y=450.0,
            width=277.0,
            height=28.0
        )

    contact_num_entry = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0
        )
    contact_num_entry.place(
            x=205.0,
            y=508.0,
            width=277.0,
            height=28.0
        )

    button_image_6 = PhotoImage(
        file=relative_to_assets("button_6.png"))
    book_button = Button(
        image=button_image_6,
        borderwidth=0,
        highlightthickness=0,
        command=lambda:submit_booking,
        relief="flat"
    )
    book_button.place(
        x=1029.0,
        y=662.0,
        width=104.0,
        height=49.0
    )

    back_button = Button(
        window,
        text="BACK",
        font=("Helvetica", 16),
        bg="black",
        fg="white",
        command=lambda: go_back()
    )
    back_button.place(
        x=900.0,
        y=662.0,
        width=104.0,
        height=49.0
    )
    label_breakdown = Label(window, text="", font=("Times New Roman", 12), justify="right")
    label_breakdown.place(x=700, y=200)
    # Dictionary to store selected car details for total price calculation

    def calculate_total_price():
        if selected_car:
            daily_rate = float(selected_car['daily_rate'])  # Fetch the daily rate from selected car

            rental_start_date_str = ren_start_entry.get()
            rental_end_date_str = ren_end_entry.get()

            try:
                rental_start_date = datetime.strptime(rental_start_date_str, '%Y-%m-%d')
                rental_end_date = datetime.strptime(rental_end_date_str, '%Y-%m-%d')

                # Calculate rental duration
                duration = (rental_end_date - rental_start_date).days
                if duration <= 0:
                    raise ValueError("Rental end date must be after start date.")

                total_price = daily_rate * duration

                breakdown_message = (
                    f"Daily Rate: RM {daily_rate:.2f}\n"
                    f"Rental Days: {duration}\n"
                    f"Total Price: RM {total_price:.2f}"
                )
                label_breakdown.config(text=breakdown_message)
                return total_price

            except ValueError as e:
                messagebox.showerror("Date Error", str(e))
                return None
        else:
            messagebox.showwarning("Selection Error", "Please select a car to book.")
            return None

    def update_total_price(event=None):
        calculate_total_price()

    calculate_button = Button(
        window,
        text="Calculate",
        font=("Helvetica", 10),
        bg="black",
        fg="white",
        command=lambda: calculate_total_price
    )
    calculate_button.place(
        x=950.0,
        y=310.0,
        width=65.0,
        height=30.0
    )
    ren_start_entry = DateEntry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0,
        date_pattern='yyyy-mm-dd'
    )
    ren_start_entry.place(
        x=730.0,
        y=390.0,
        width=277.0,
        height=28.0
    )

    birthdate_entry = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    birthdate_entry.place(
        x=170.0,
        y=566.0,
        width=277.0,
        height=29.0
    )

    ren_end_entry = DateEntry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0,
        date_pattern='yyyy-mm-dd'
    )
    ren_end_entry.place(
        x=730.0,
        y=450.0,
        width=277.0,
        height=28.0
    )

    def submit_booking():
        total_price = calculate_total_price()
        if total_price is None:
            return

        customer_name = name_entry.get()
        email = email_entry.get()
        contact_number = contact_num_entry.get()
        date_of_birth = birthdate_entry.get()
        rental_start_date = ren_start_entry.get()
        rental_end_date = ren_end_entry.get()

        # Insert booking into the database
        conn = connect_db()
        cursor = conn.cursor()
        cursor.execute(""" 
            INSERT INTO bookings (car_id, customer_name, email, contact_number, date_of_birth, rental_start_date, rental_end_date, total_price) 
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            car_id,
            customer_name,
            email,
            contact_number,
            date_of_birth,
            rental_start_date,
            rental_end_date,
            total_price
        ))

        conn.commit()
        conn.close()

        # Show a success message
        messagebox.showinfo("Success", "Booking submitted successfully!")
        window.destroy()  # Close the booking window after submission

    window.resizable(False, False)
    window.mainloop()

import sys

if __name__ == "__main__":
    # Check if car_id was passed as a command-line argument
    if len(sys.argv) > 1:
        car_id = int(sys.argv[1])  # Convert the argument to an integer
    else:
        car_id = 1  # Default to a specific car_id if none is passed

    create_booking_page(car_id)
