
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\User\Documents\Ruxin file\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1221x773")
window.configure(bg = "#FFFFFF")


canvas = Canvas(window,bg = "#FFFFFF",
height = 773,
    width = 1221,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1221.0,
    113.0,
    fill="#DFDFDF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    86.0,
    57.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=1126.0,
    y=31.0,
    width=49.0,
    height=49.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=969.0,
    y=36.0,
    width=132.0,
    height=40.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=700.0,
    y=30.0,
    width=84.0,
    height=52.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=854.0,
    y=30.0,
    width=90.0,
    height=52.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=784.0,
    y=30.0,
    width=70.0,
    height=52.0
)

canvas.create_text(
    92.0,
    305.0,
    anchor="nw",
    text="Car Model:",
    fill="#000000",
    font=("KaiseiDecol Medium", 16 * -1)
)

canvas.create_text(
    54.0,
    266.0,
    anchor="nw",
    text="Filter:",
    fill="#000000",
    font=("KaiseiDecol Medium", 18 * -1)
)

canvas.create_text(
    47.0,
    143.0,
    anchor="nw",
    text="Cars",
    fill="#000000",
    font=("KaiseiDecol Medium", 40 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    142.5,
    356.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=54.0,
    y=339.0,
    width=177.0,
    height=33.0
)

canvas.create_text(
    80.0,
    388.0,
    anchor="nw",
    text="Min Price(RM):",
    fill="#000000",
    font=("KaiseiDecol Medium", 16 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    140.5,
    439.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=52.0,
    y=422.0,
    width=177.0,
    height=33.0
)

canvas.create_text(
    116.0,
    553.0,
    anchor="nw",
    text="Seats:",
    fill="#000000",
    font=("KaiseiDecol Medium", 16 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    140.5,
    605.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=52.0,
    y=588.0,
    width=177.0,
    height=32.0
)

canvas.create_text(
    79.0,
    470.0,
    anchor="nw",
    text="Max Price(RM):",
    fill="#000000",
    font=("KaiseiDecol Medium", 16 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    140.5,
    522.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=52.0,
    y=505.0,
    width=177.0,
    height=32.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=102.0,
    y=671.0,
    width=77.0,
    height=28.0
)

canvas.create_rectangle(
    33.0,
    246.0,
    249.0,
    719.0,
    fill="#B0B0B0",
    outline="")

canvas.create_rectangle(
    316.0,
    140.0,
    578.0,
    309.0,
    fill="#FFFDFD",
    outline="")

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    446.0,
    194.0,
    image=image_image_2
)

canvas.create_rectangle(
    614.0,
    140.0,
    877.0,
    309.0,
    fill="#FFFDFD",
    outline="")

canvas.create_rectangle(
    913.0,
    140.0,
    1175.0,
    309.0,
    fill="#FFFDFD",
    outline="")

canvas.create_rectangle(
    316.0,
    353.0,
    578.0,
    522.0,
    fill="#FFFDFD",
    outline="")

canvas.create_rectangle(
    614.0,
    353.0,
    877.0,
    522.0,
    fill="#FFFDFD",
    outline="")

canvas.create_rectangle(
    913.0,
    353.0,
    1175.0,
    522.0,
    fill="#FFFDFD",
    outline="")

canvas.create_rectangle(
    316.0,
    566.0,
    578.0,
    735.0,
    fill="#FFFDFD",
    outline="")

canvas.create_rectangle(
    614.0,
    566.0,
    877.0,
    735.0,
    fill="#FFFDFD",
    outline="")

canvas.create_rectangle(
    913.0,
    566.0,
    1175.0,
    735.0,
    fill="#FFFDFD",
    outline="")

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    746.0,
    194.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    1044.0,
    194.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    1043.0,
    410.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    746.0,
    410.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    447.0,
    410.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    446.0,
    623.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    746.0,
    623.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    1044.0,
    623.0,
    image=image_image_10
)
window.resizable(False, False)
window.mainloop()
