
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import subprocess,sys


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\User\Documents\Ruxin file\build\assets\frame8")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def view_booking_button(window):
    window.destroy()
    subprocess.Popen(["python",r"C:\Users\User\Documents\Ruxin file\build\view_booking.py"])

def notifications_button(window):
    window.destroy()
    subprocess.Popen(["python",r"C:\Users\User\Documents\Ruxin file\build\notification.py"])

def history_button(window):
    window.withdraw()
    subprocess.Popen(["python",'history.py'])

def log_out_button(window):
    window.destroy()
    subprocess.Popen(["python",r"C:\Users\User\Documents\Ruxin file\build\first_page.py"])

def promo_button(window):
    window.destroy()
    subprocess.Popen(["python",r"C:\Users\User\Documents\Ruxin file\build\promo.py"])

def cars_button(window):
    window.destroy()
    subprocess.Popen(["python", r"C:\Users\User\Documents\Ruxin file\build\car.py"])

window = Tk()

window.geometry("1221x773")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 773,
    width = 1221,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    1.0,
    1220.0,
    166.0,
    fill="#DFDFDF",
    outline="")

canvas.create_rectangle(
    0.0,
    1.0,
    1220.0,
    166.0,
    fill="#DFDFDF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    86.0,
    78.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=1119.0,
    y=56.0,
    width=58.0,
    height=58.0
)


button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: view_booking_button(window),
    relief="flat"
)
button_3.place(
    x=124.0,
    y=250.0,
    width=972.2060546875,
    height=71.55624389648438
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: notifications_button(window),
    relief="flat"
)
button_4.place(
    x=124.0,
    y=405.0,
    width=972.2060546875,
    height=71.55624389648438
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: history_button(window),
    relief="flat"
)
button_5.place(
    x=124.0,
    y=554.07568359375,
    width=972.2060546875,
    height=71.55624389648438
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: log_out_button(window),
    relief="flat"
)
button_6.place(
    x=547.0,
    y=681.0,
    width=128.0,
    height=67.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: promo_button(window),
    relief="flat"
)
button_8.place(
    x=815.0,
    y=58.0,
    width=107.0,
    height=62.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda:cars_button(window),
    relief="flat"
)
button_9.place(
    x=732.0,
    y=58.0,
    width=83.0,
    height=62.0
)
window.resizable(False, False)
window.mainloop()
