
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import sqlite3
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,messagebox
import subprocess,sys


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\User\Documents\Ruxin file\build\assets\frame8")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def connect_db():
    conn = sqlite3.connect(r"C:\Users\User\Documents\Ruxin file\build\Car_Rental.db")
    return conn

def get_user_id(user_id):
    conn = connect_db()
    cursor = conn.cursor()

    try:
        cursor.execute("SELECT id, username, email FROM Users_details WHERE id = ?", (user_id,))
        user = cursor.fetchone()

        if user:
            user_details = {
                "id": user[0],
                "username": user[1],
                "email": user[2],
            }
            return user_details
        else:
            print(f"No user found with ID {user_id}.")
            return None
    finally:
        conn.close()


def show_user_details(user_id):
    user = get_user_id(user_id)
    if user:
        print(f"User Details: {user}")  # Replace 'Users_details' with 'user'
    else:
        print("User not found.")

def view_booking_button(user_id):
    window.withdraw()
    subprocess.Popen([sys.executable,r"C:\Users\User\Documents\Ruxin file\build\view_booking.py",str(user_id)])

def history_button(user_id):
    window.withdraw()
    subprocess.Popen([sys.executable,r"C:\Users\User\Documents\Ruxin file\build\history.py",str(user_id)])

def log_out_button():
    window.destroy()
    subprocess.Popen([sys.executable,r"C:\Users\User\Documents\Ruxin file\build\first_page.py"])

def promo_button(user_id):
    window.withdraw()
    subprocess.Popen([sys.executable,r"C:\Users\User\Documents\Ruxin file\build\promo.py",str(user_id)])

def cars_button(user_id):
    window.withdraw()
    subprocess.Popen([sys.executable, r"C:\Users\User\Documents\Ruxin file\build\car.py",str(user_id)])

window = Tk()

window.geometry("1221x773")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 773,
    width = 1221,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    1.0,
    1220.0,
    166.0,
    fill="#DFDFDF",
    outline="")

canvas.create_rectangle(
    0.0,
    1.0,
    1220.0,
    166.0,
    fill="#DFDFDF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    86.0,
    78.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda:print("button 1 clicked"),
    relief="flat"
)
button_1.place(
    x=1126.0,
    y=56.0,
    width=58.0,
    height=58.0
)


button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: view_booking_button(user_id),
    relief="flat"
)
button_3.place(
    x=124.0,
    y=300.0,
    width=972.2060546875,
    height=71.55624389648438
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: history_button(user_id),
    relief="flat"
)
button_5.place(
    x=124.0,
    y=500,
    width=972.2060546875,
    height=71.55624389648438
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: log_out_button(),
    relief="flat"
)
button_6.place(
    x=547.0,
    y=681.0,
    width=128.0,
    height=67.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: promo_button(user_id),
    relief="flat"
)
button_8.place(
    x=1010.0,
    y=58.0,
    width=90.0,
    height=52.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda:cars_button(user_id),
    relief="flat"
)
button_9.place(
    x=917.0,
    y=58.0,
    width=70.0,
    height=52.0
)
if len(sys.argv) < 2:
    messagebox.showerror("Error", "User ID not provided.")
    sys.exit(1)

user_id = int(sys.argv[1])
show_user_details(user_id)
window.resizable(False, False)
window.mainloop()
