
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\User\Documents\Ruxin file\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1221x773")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 773,
    width = 1221,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    56.0,
    152.0,
    anchor="nw",
    text="Promo",
    fill="#000000",
    font=("KaiseiDecol Medium", 40 * -1)
)

canvas.create_text(
    59.0,
    541.0,
    anchor="nw",
    text="Contact",
    fill="#000000",
    font=("KaiseiDecol Medium", 40 * -1)
)

canvas.create_text(
    141.0,
    627.0,
    anchor="nw",
    text="017-789 1011",
    fill="#000000",
    font=("KaiseiDecol Medium", 32 * -1)
)

canvas.create_rectangle(
    72.0,
    241.0,
    1149.0,
    514.0,
    fill="#FFFDFD",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    310.0,
    378.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    0.0,
    1221.0,
    113.0,
    fill="#DFDFDF",
    outline="")

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    86.0,
    57.0,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=1126.0,
    y=31.0,
    width=49.0,
    height=49.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=969.0,
    y=36.0,
    width=132.0,
    height=40.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=854.0,
    y=30.0,
    width=90.0,
    height=52.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=784.0,
    y=30.0,
    width=70.0,
    height=52.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    85.0,
    642.0,
    image=image_image_3
)
window.resizable(False, False)
window.mainloop()
