
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Toplevel,Text, Button, PhotoImage,ttk, messagebox,Label
import subprocess
import sqlite3,os,sys
from PIL import Image, ImageTk

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\User\Documents\Ruxin file\build\assets\frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

# Connect to the database
def connect_db():
    conn = sqlite3.connect(r"C:\Users\User\Documents\Ruxin file\build\Car_Rental.db")
    return conn

def show_booking_details(user_id):
    conn = connect_db()
    cursor = conn.cursor()

    cursor.execute('''
        SELECT b.booking_id,c.registration_number, c.make_and_model,
               b.rental_start_date, b.rental_end_date, b.total_price,
               COALESCE(julianday(b.rental_end_date) - julianday(b.rental_start_date), 0) AS days, b.status,c.image_path,b.user_id
        FROM bookings b
        JOIN cars_details c ON b.car_id = c.id
        WHERE b.user_id =?
    ''',(user_id,))

    rows = cursor.fetchall()
    conn.close()

    # Clear previous bookings from the Treeview
    for item in treeview_bookings.get_children():
        treeview_bookings.delete(item)

    # Insert the rows for the logged-in user
    for row in rows:
        formatted_row = list(row)
        formatted_row[5] = f"{formatted_row[5]:.2f}"  # Assuming daily_rate is at index 4
        treeview_bookings.insert("", "end", values=tuple(formatted_row))

def on_treeview_select(event):
    selected_item = treeview_bookings.selection()
    if selected_item:
        item = treeview_bookings.item(selected_item)
        booking_status = item['values'][7]

        if booking_status.lower() == "Approved":
            clear_button.config(state="disabled")

        elif booking_status.lower() == "pending":
            clear_button.config(state="normal")

        else:
            clear_button.config(state="disabled")
    else:
        messagebox.showwarning("Selection Error", "No booking selected.")
        return None

def open_payment_window():
    selected_item = treeview_bookings.selection()

    if selected_item:
        item = treeview_bookings.item(selected_item)
        booking_id = item['values'][0]  # Get the Booking ID from the selected row
        user_id = item['values'][9]  # Get the user ID from the selected row (ensure it's available)
        booking_status = item['values'][7].strip().lower()
        customer_name = item['values'][1]

        if booking_status != "approved":
            messagebox.showwarning("Action Not Allowed", "Payment can only be made for approved bookings.")
            return

        try:
            subprocess.Popen([sys.executable, r"C:\Users\User\Documents\Ruxin file\build\payment.py", str(booking_id), str(user_id)])
            messagebox.showinfo("Payment", f"Payment window opened for {customer_name}.")

            # Disable the payment button after initiating payment
            payment_button.config(state="disabled")
        except Exception as e:
            messagebox.showerror("Error", f"Failed to open payment window: {e}")
    else:
        messagebox.showwarning("No Booking Selected", "Please select a booking first.")

def clear_booking():
    selected_item = treeview_bookings.selection()
    if selected_item:
        item = treeview_bookings.item(selected_item)
        booking_id = item['values'][0]
        booking_status = item['values'][7]


        if messagebox.askyesno("Confirm Deletion", "Are you sure you want to delete this booking?"):
            conn = connect_db()
            cursor = conn.cursor()
            cursor.execute('DELETE FROM bookings WHERE booking_id = ?', (booking_id,))
            conn.commit()
            conn.close()

            # Refresh the booking details after deletion
            show_booking_details(user_id)
            messagebox.showinfo("Success", "Booking cleared successfully!")

def display_selected_image(event):
    selected_item = treeview_bookings.selection()
    if selected_item:
        item = treeview_bookings.item(selected_item)
        reg_num = item['values'][1]  # Get car ID from the selected row
    
        conn = connect_db()
        cursor = conn.cursor()
        cursor.execute(f"SELECT image_path FROM cars_details WHERE registration_number = \'{reg_num}\'")
        
        image_path = cursor.fetchone()

        print(image_path)
        if image_path and image_path[0]:
            print(1)
            try:
                print(2)
                img = Image.open(image_path[0])
                img = img.resize((300, 300), Image.Resampling.LANCZOS)
                img = ImageTk.PhotoImage(img)

                # Display the image
                label_image.config(image=img)
                label_image.image = img
            except Exception as e:
                print(f"Error loading image: {e}")
                label_image.config(image='')
        else:
            label_image.config(image='')
        conn.close()
        
def go_back(user_id):
    window.withdraw()  # Close the current window
    subprocess.Popen([sys.executable, r"C:\Users\User\Documents\Ruxin file\build\profile.py",str(user_id)])  # Open the customer panel

def promo_button(user_id):
    window.withdraw()
    subprocess.Popen([sys.executable,r"C:\Users\User\Documents\Ruxin file\build\promo.py",str(user_id)])

def cars_button(user_id):
    window.withdraw()
    subprocess.Popen([sys.executable, r"C:\Users\User\Documents\Ruxin file\build\car.py",str(user_id)])

def profile_page(user_id):
    window.withdraw()
    subprocess.Popen([sys.executable,r"C:\Users\User\Documents\Ruxin file\build\profile.py",str(user_id)])


window = Tk()
window.geometry("1221x773")
window.configure(bg="#FFFFFF")

canvas = Canvas(window, bg="#FFFFFF", height=773, width=1221, bd=0, highlightthickness=0, relief="ridge")

canvas.place(x=0, y=0)
canvas.create_rectangle(0.0, 0.0, 1221.0, 113.0, fill="#DFDFDF", outline="")


treeview_bookings = ttk.Treeview(window, columns=("Booking ID", "Reg. No.", "Make & Model",
                                                      "Start Date", "End Date", "Total Price",
                                                      "No. of Days", "Status"), show="headings")
treeview_bookings.heading("Booking ID", text="Booking ID")
treeview_bookings.heading("Reg. No.", text="Reg. No.")
treeview_bookings.heading("Make & Model", text="Make & Model")
treeview_bookings.heading("Start Date", text="Start Date")
treeview_bookings.heading("End Date", text="End Date")
treeview_bookings.heading("Total Price", text="Total Price (RM)")
treeview_bookings.heading("No. of Days", text="No. of Days")
treeview_bookings.heading("Status", text="Status")

treeview_bookings.column("Booking ID", width=80, anchor="center")
treeview_bookings.column("Reg. No.", width=60, anchor="center")
treeview_bookings.column("Make & Model", width=110, anchor="center")
treeview_bookings.column("Start Date", width=90, anchor="center")
treeview_bookings.column("End Date", width=90, anchor="center")
treeview_bookings.column("Total Price", width=100, anchor="center")
treeview_bookings.column("No. of Days", width=90, anchor="center")
treeview_bookings.column("Status", width=90, anchor="center")
    
treeview_bookings.place(x=25, y=280, width=850, height=300)
treeview_bookings.bind("<<TreeviewSelect>>", display_selected_image)

Button(window, text="Refresh Bookings", command=lambda: show_booking_details(user_id), bg="red", fg="black",font=("KaiseiDecol Medium", 16 * -1)).place(x=25, y=600, width=150, height=50)

Button(window, text="Clear Booking", command=lambda:clear_booking(), bg="orange", fg="black",font=("KaiseiDecol Medium", 16 * -1)).place(x=220, y=600, width=150, height=50)

Button(window, text="Back", command=lambda: go_back(user_id), bg="yellow", fg="black",font=("KaiseiDecol Medium", 16 * -1)).place(x=425, y=600, width=50, height=50)

image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
canvas.create_image(86.0, 57.0, image=image_image_1)

button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
button_1 = Button(image=button_image_1, borderwidth=0, highlightthickness=0, command=lambda: profile_page(user_id),relief="flat")
button_1.place(x=1126.0, y=31.0, width=49.0, height=49.0)

button_image_4 = PhotoImage(file=relative_to_assets("button_4.png"))
button_4 = Button(image=button_image_4, borderwidth=0, highlightthickness=0, command=lambda: promo_button(user_id),relief="flat")
button_4.place(x=1010.0, y=30.0, width=90.0, height=52.0)

button_image_5 = PhotoImage(file=relative_to_assets("button_5.png"))
button_5 = Button(image=button_image_5, borderwidth=0, highlightthickness=0, command=lambda: cars_button(user_id),relief="flat")
button_5.place(x=917.0, y=30.0, width=70.0, height=52.0)

canvas.create_text(56.0, 168.0, anchor="nw", text="View Booking", fill="#000000",font=("KaiseiDecol Medium", 40 * -1))

label_image = Label(window)
label_image.place(x=900, y=280, width=300, height=300)

payment_button = Button(window, text="Make Payment", bg="blue", fg="white", font=("Arial", 14), command=open_payment_window)
payment_button.place(x=650, y=600, width=150, height=50)

current_user_id = 123
user_id = current_user_id if len(sys.argv) <= 1 else int(sys.argv[1])

show_booking_details(user_id)
window.mainloop()

